version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zk:
    image: 'zookeeper'
    restart: always
    hostname: zk
    ports:
      - 2181:2181
    networks:
      - app-tier
  zkui:
    image: 'elkozmon/zoonavigator'
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - app-tier
  etcd:
    image: 'bitnami/etcd:latest'
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 3000:2379
      - 3001:2380
    networks:
      - app-tier
  etcdui:
    image: 'evildecay/etcdkeeper'
    ports:
        - 9000:8080
    networks:
    - app-tier
  
  config:
    image: 'sweets:0.1'
    restart: always
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    hostname: config
    ports:
      - 50051:50051
    networks:
      - app-tier